[metadata]
name = "Kanagawa"
author = "retoo"
isDark = true

[dark]
primary = "#76946a"
onPrimary = "#1f1f28"
secondary = "#c0a36e"
onSecondary = "#1f1f28"
tertiary = "#7e9cd8"
onTertiary = "#1f1f28"
error = "#c34043"
onError = "#1f1f28"
surface = "#1f1f28"
onSurface = "#c8c093"
surfaceVariant = "#2a2a37"
onSurfaceVariant = "#717c7c"
outline = "#363646"
shadow = "#1f1f28"
hover = "#7e9cd8"
onHover = "#1f1f28"

[dark.terminal.normal]
black = "#090618"
red = "#c34043"
green = "#76946a"
yellow = "#c0a36e"
blue = "#7e9cd8"
magenta = "#957fb8"
cyan = "#6a9589"
white = "#c8c093"

[dark.terminal.bright]
black = "#727169"
red = "#e82424"
green = "#98bb6c"
yellow = "#e6c384"
blue = "#7fb4ca"
magenta = "#938aa9"
cyan = "#7aa89f"
white = "#dcd7ba"

[dark.terminal]
foreground = "#dcd7ba"
background = "#1f1f28"
selectionFg = "#c8c093"
selectionBg = "#2d4f67"
cursorText = "#1f1f28"
cursor = "#c8c093"

[light]
mPrimary = "#6f894e"
mOnPrimary = "#f2ecbc"
mSecondary = "#77713f"
mOnSecondary = "#f2ecbc"
mTertiary = "#4d699b"
mOnTertiary = "#f2ecbc"
mError = "#c84053"
mOnError = "#f2ecbc"
mSurface = "#f2ecbc"
mOnSurface = "#545464"
mSurfaceVariant = "#e5ddb0"
mOnSurfaceVariant = "#8a8980"
mOutline = "#cfc49c"
mShadow = "#f2ecbc"
mHover = "#4d699b"
mOnHover = "#f2ecbc"

[light.terminal.normal]
black = "#1F1F28"
red = "#c84053"
green = "#6f894e"
yellow = "#77713f"
blue = "#4d699b"
magenta = "#b35b79"
cyan = "#597b75"
white = "#545464"

[light.terminal.bright]
black = "#8a8980"
red = "#d7474b"
green = "#6e915f"
yellow = "#836f4a"
blue = "#6693bf"
magenta = "#624c83"
cyan = "#5e857a"
white = "#43436c"

[light.terminal]
foreground = "#545464"
background = "#f2ecbc"
selectionFg = "#f2ecbc"
selectionBg = "#c9cbd1"
cursorText = "#f2ecbc"
cursor = "#43436c"