[metadata]
name = "Nord"
author = " arcticicestudio"
isDark = false

[dark]
primary = "#8fbcbb"
onPrimary = "#2e3440"
secondary = "#88c0d0"
onSecondary = "#2e3440"
tertiary = "#5e81ac"
onTertiary = "#2e3440"
error = "#bf616a"
onError = "#2e3440"
surface = "#2e3440"
onSurface = "#eceff4"
surfaceVariant = "#3b4252"
onSurfaceVariant = "#d8dee9"
outline = "#505a70"
shadow = "#2e3440"
hover = "#5e81ac"
onHover = "#2e3440"

[dark.terminal.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[dark.terminal.bright]
black = "#596377"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[dark.terminal]
foreground = "#d8dee9"
background = "#2e3440"
selectionFg = "#4c566a"
selectionBg = "#eceff4"
cursorText = "#282828"
cursor = "#eceff4"

[light]
mPrimary = "#5e81ac"
mOnPrimary = "#eceff4"
mSecondary = "#64adc2"
mOnSecondary = "#eceff4"
mTertiary = "#6fa9a8"
mOnTertiary = "#eceff4"
mError = "#bf616a"
mOnError = "#eceff4"
mSurface = "#eceff4"
mOnSurface = "#2e3440"
mSurfaceVariant = "#e5e9f0"
mOnSurfaceVariant = "#4c566a"
mOutline = "#c5cedd"
mShadow = "#d8dee9"
mHover = "#6fa9a8"
mOnHover = "#eceff4"

[light.terminal.normal]
black = "#3b4252"
red = "#bf616a"
green = "#96b17f"
yellow = "#c5a565"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#7bb3c3"
white = "#a5abb6"

[light.terminal.bright]
black = "#4c566a"
red = "#bf616a"
green = "#96b17f"
yellow = "#c5a565"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#82afae"
white = "#eceff4"

[light.terminal]
foreground = "#414858"
background = "#e5e9f0"
selectionFg = "#4c556a"
selectionBg = "#d8dee9"
cursorText = "#3b4252"
cursor = "#7bb3c3"