[metadata]
name = "Tokyo-Night"
author = "Michele"
isDark = true

[dark]
primary = "#7aa2f7"
onPrimary = "#16161e"
secondary = "#bb9af7"
onSecondary = "#16161e"
tertiary = "#9ece6a"
onTertiary = "#16161e"
error = "#f7768e"
onError = "#16161e"
surface = "#1a1b26"
onSurface = "#c0caf5"
surfaceVariant = "#24283b"
onSurfaceVariant = "#9aa5ce"
outline = "#353D57"
shadow = "#15161e"
hover = "#9ece6a"
onHover = "#16161e"

[dark.terminal.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[dark.terminal.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[dark.terminal]
foreground = "#c0caf5"
background = "#1a1b26"
selectionFg = "#c0caf5"
selectionBg = "#283457"
cursorText = "#1a1b26"
cursor = "#c0caf5"

[light]
mPrimary = "#2e7de9"
mOnPrimary = "#e1e2e7"
mSecondary = "#9854f1"
mOnSecondary = "#e1e2e7"
mTertiary = "#587539"
mOnTertiary = "#e1e2e7"
mError = "#f52a65"
mOnError = "#e1e2e7"
mSurface = "#e1e2e7"
mOnSurface = "#3760bf"
mSurfaceVariant = "#d0d5e3"
mOnSurfaceVariant = "#6172b0"
mOutline = "#b4b5b9"
mShadow = "#a8aecb"
mHover = "#587539"
mOnHover = "#e1e2e7"

[light.terminal.normal]
black = "#e9e9ed"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#6172b0"

[light.terminal.bright]
black = "#a1a6c5"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "#3760bf"

[light.terminal]
foreground = "#3760bf"
background = "#e1e2e7"
selectionFg = "#3760bf"
selectionBg = "#99a7df"
cursorText = "#e1e2e7"
cursor = "#3760bf"