use std::env;
use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("version.rs");

    let version = get_version();
    let git_sha = get_git_sha();
    let git_tag = get_git_tag();

    let git_tag_str = git_tag
        .as_ref()
        .map(|t| format!("Some(\"{}\")", t))
        .unwrap_or_else(|| "None".to_string());

    let content = format!(
        r#"// Auto-generated by build.rs
pub const VERSION: &str = "{}";
pub const GIT_SHA: &str = "{}";
pub const GIT_TAG: Option<&str> = {};
"#,
        version, git_sha, git_tag_str
    );

    fs::write(&dest_path, content).expect("Failed to write version.rs");

    println!("cargo:rustc-env=CRAWLDS_VERSION={}", version);
    println!("cargo:rustc-env=CRAWLDS_GIT_SHA={}", git_sha);
    if let Some(ref tag) = git_tag {
        println!("cargo:rustc-env=CRAWLDS_GIT_TAG={}", tag);
    }
}

fn get_version() -> String {
    if let Ok(tag) = Command::new("git")
        .args(["describe", "--tags", "--abbrev=0"])
        .output()
    {
        if tag.status.success() {
            return String::from_utf8_lossy(&tag.stdout).trim().to_string();
        }
    }
    env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "unknown".to_string())
}

fn get_git_sha() -> String {
    if let Ok(sha) = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()
    {
        if sha.status.success() {
            return String::from_utf8_lossy(&sha.stdout).trim().to_string();
        }
    }
    "unknown".to_string()
}

fn get_git_tag() -> Option<String> {
    if let Ok(tag) = Command::new("git")
        .args(["describe", "--tags", "--exact-match", "HEAD"])
        .output()
    {
        if tag.status.success() {
            return Some(String::from_utf8_lossy(&tag.stdout).trim().to_string());
        }
    }
    None
}
