//! Material Design 3 tone value definitions
//!
//! Defines tone values for all M3 color roles.

#[derive(Clone, Copy, Debug)]
pub struct ToneValues {
    pub primary: u8,
    pub on_primary: u8,
    pub primary_container: u8,
    pub on_primary_container: u8,
    pub secondary: u8,
    pub on_secondary: u8,
    pub secondary_container: u8,
    pub on_secondary_container: u8,
    pub tertiary: u8,
    pub on_tertiary: u8,
    pub tertiary_container: u8,
    pub on_tertiary_container: u8,
    pub error: u8,
    pub on_error: u8,
    pub error_container: u8,
    pub on_error_container: u8,
    pub surface: u8,
    pub on_surface: u8,
    pub surface_variant: u8,
    pub on_surface_variant: u8,
    pub surface_container_lowest: u8,
    pub surface_container_low: u8,
    pub surface_container: u8,
    pub surface_container_high: u8,
    pub surface_container_highest: u8,
    pub outline: u8,
    pub outline_variant: u8,
    pub shadow: u8,
    pub scrim: u8,
    pub inverse_surface: u8,
    pub inverse_on_surface: u8,
    pub inverse_primary: u8,
    pub background: u8,
    pub on_background: u8,
    pub surface_dim: u8,
    pub surface_bright: u8,
}

pub const DARK_TONES: ToneValues = ToneValues {
    primary: 80,
    on_primary: 20,
    primary_container: 30,
    on_primary_container: 90,
    secondary: 80,
    on_secondary: 20,
    secondary_container: 30,
    on_secondary_container: 90,
    tertiary: 80,
    on_tertiary: 20,
    tertiary_container: 30,
    on_tertiary_container: 90,
    error: 80,
    on_error: 20,
    error_container: 30,
    on_error_container: 90,
    surface: 6,
    on_surface: 90,
    surface_variant: 30,
    on_surface_variant: 80,
    surface_container_lowest: 4,
    surface_container_low: 10,
    surface_container: 12,
    surface_container_high: 17,
    surface_container_highest: 22,
    outline: 60,
    outline_variant: 30,
    shadow: 0,
    scrim: 0,
    inverse_surface: 90,
    inverse_on_surface: 20,
    inverse_primary: 40,
    background: 6,
    on_background: 90,
    surface_dim: 6,
    surface_bright: 24,
};

pub const LIGHT_TONES: ToneValues = ToneValues {
    primary: 40,
    on_primary: 100,
    primary_container: 90,
    on_primary_container: 10,
    secondary: 40,
    on_secondary: 100,
    secondary_container: 90,
    on_secondary_container: 10,
    tertiary: 40,
    on_tertiary: 100,
    tertiary_container: 90,
    on_tertiary_container: 10,
    error: 40,
    on_error: 100,
    error_container: 90,
    on_error_container: 10,
    surface: 98,
    on_surface: 10,
    surface_variant: 90,
    on_surface_variant: 30,
    surface_container_lowest: 100,
    surface_container_low: 96,
    surface_container: 94,
    surface_container_high: 92,
    surface_container_highest: 90,
    outline: 50,
    outline_variant: 80,
    shadow: 0,
    scrim: 0,
    inverse_surface: 20,
    inverse_on_surface: 95,
    inverse_primary: 80,
    background: 98,
    on_background: 10,
    surface_dim: 87,
    surface_bright: 98,
};

pub const MONOCHROME_DARK_TONES: ToneValues = ToneValues {
    primary: 100,
    on_primary: 10,
    primary_container: 85,
    on_primary_container: 0,
    secondary: 80,
    on_secondary: 20,
    secondary_container: 30,
    on_secondary_container: 90,
    tertiary: 90,
    on_tertiary: 10,
    tertiary_container: 60,
    on_tertiary_container: 0,
    ..DARK_TONES
};

pub const MONOCHROME_LIGHT_TONES: ToneValues = ToneValues {
    primary: 0,
    on_primary: 90,
    primary_container: 25,
    on_primary_container: 100,
    secondary: 25,
    on_secondary: 90,
    secondary_container: 90,
    on_secondary_container: 10,
    tertiary: 25,
    on_tertiary: 90,
    tertiary_container: 49,
    on_tertiary_container: 100,
    ..LIGHT_TONES
};

pub const MUTED_DARK_TONES: ToneValues = ToneValues {
    primary: 35,
    on_primary: 95,
    primary_container: 15,
    on_primary_container: 92,
    secondary: 28,
    on_secondary: 92,
    secondary_container: 18,
    on_secondary_container: 85,
    tertiary: 22,
    on_tertiary: 92,
    tertiary_container: 15,
    on_tertiary_container: 85,
    error: 70,
    on_error: 18,
    error_container: 30,
    on_error_container: 95,
    surface: 8,
    on_surface: 80,
    surface_variant: 18,
    on_surface_variant: 70,
    surface_container_lowest: 6,
    surface_container_low: 12,
    surface_container: 16,
    surface_container_high: 20,
    surface_container_highest: 24,
    outline: 50,
    outline_variant: 28,
    shadow: 0,
    scrim: 0,
    inverse_surface: 85,
    inverse_on_surface: 12,
    inverse_primary: 45,
    background: 8,
    on_background: 80,
    surface_dim: 6,
    surface_bright: 18,
};

pub const MUTED_LIGHT_TONES: ToneValues = ToneValues {
    primary: 35,
    on_primary: 98,
    primary_container: 90,
    on_primary_container: 12,
    secondary: 28,
    on_secondary: 98,
    secondary_container: 85,
    on_secondary_container: 12,
    tertiary: 22,
    on_tertiary: 98,
    tertiary_container: 85,
    on_tertiary_container: 12,
    error: 70,
    on_error: 98,
    error_container: 90,
    on_error_container: 12,
    surface: 95,
    on_surface: 15,
    surface_variant: 85,
    on_surface_variant: 28,
    surface_container_lowest: 100,
    surface_container_low: 96,
    surface_container: 92,
    surface_container_high: 88,
    surface_container_highest: 85,
    outline: 40,
    outline_variant: 60,
    shadow: 0,
    scrim: 0,
    inverse_surface: 90,
    inverse_on_surface: 12,
    inverse_primary: 80,
    background: 95,
    on_background: 15,
    surface_dim: 90,
    surface_bright: 100,
};
